config/routes.rb
Rails.application.routes.draw do
  resources :commands
  get 'home/index'

   root 'home#index'

end

app/models/command.rb
class Command < ActiveRecord::Base
	validates :numclient, :presence => true
	validates :refproduit, :presence => true,
                    :length => { :minimum => 4 }
    validates :quantitearticle, :presence => true,
                    :length => { :minimum => 1 }

end
#  classe Command hérite de ActiveRecord::Base. Active Record fournit une grande partie des fonctionnalités de votre modèle Rails,
# notamment les opérations CRUD – Create, Read, Update, Destroy (Créer, Lire, Modifier, Détruire)- de base, la validation des données, ainsi que le support d’une recherche sophistiquée et la possibilité de lier des modèles entre eux.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:numclient, :refproduit, :article, :descriptif, :numcommande, :quantitearticle, :totalprixarticle, :totalprixcommande, :date, :produit_id, :validation)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/commands/_form.html.erb
<!-- un “partial” (vue partielle) pour contrôler l’apparence du formulaire utilisé par les vues edit et new-->

<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numclient %><br>
    <%= f.number_field :numclient %>
  </div>
  <div class="field">
    <%= f.label :refproduit %><br>
    <%= f.text_field :refproduit %>
  </div>
  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :descriptif %><br>
    <%= f.text_field :descriptif %>
  </div>
  <div class="field">
    <%= f.label :numcommande %><br>
    <%= f.number_field :numcommande %>
  </div>
  <div class="field">
    <%= f.label :quantitearticle %><br>
    <%= f.number_field :quantitearticle %>
  </div>
  <div class="field">
    <%= f.label :totalprixarticle %><br>
    <%= f.text_field :totalprixarticle %>
  </div>
  <div class="field">
    <%= f.label :totalprixcommande %><br>
    <%= f.text_field :totalprixcommande %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :produit_id %><br>
    <%= f.number_field :produit_id %>
  </div>
  <div class="field">
    <%= f.label :validation %><br>
    <%= f.text_area :validation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commands</h1>

<table>
  <thead>
    <tr>
      <th>Numclient</th>
      <th>Refproduit</th>
      <th>Article</th>
      <th>Descriptif</th>
      <th>Numcommande</th>
      <th>Quantitearticle</th>
      <th>Totalprixarticle</th>
      <th>Totalprixcommande</th>
      <th>Date</th>
      <th>Produit</th>
      <th>Validation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= command.numclient %></td>
        <td><%= command.refproduit %></td>
        <td><%= command.article %></td>
        <td><%= command.descriptif %></td>
        <td><%= command.numcommande %></td>
        <td><%= command.quantitearticle %></td>
        <td><%= command.totalprixarticle %></td>
        <td><%= command.totalprixcommande %></td>
        <td><%= command.date %></td>
        <td><%= command.produit_id %></td>
        <td><%= command.validation %></td>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New Command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numclient:</strong>
  <%= @command.numclient %>
</p>

<p>
  <strong>Refproduit:</strong>
  <%= @command.refproduit %>
</p>

<p>
  <strong>Article:</strong>
  <%= @command.article %>
</p>

<p>
  <strong>Descriptif:</strong>
  <%= @command.descriptif %>
</p>

<p>
  <strong>Numcommande:</strong>
  <%= @command.numcommande %>
</p>

<p>
  <strong>Quantitearticle:</strong>
  <%= @command.quantitearticle %>
</p>

<p>
  <strong>Totalprixarticle:</strong>
  <%= @command.totalprixarticle %>
</p>

<p>
  <strong>Totalprixcommande:</strong>
  <%= @command.totalprixcommande %>
</p>

<p>
  <strong>Date:</strong>
  <%= @command.date %>
</p>

<p>
  <strong>Produit:</strong>
  <%= @command.produit_id %>
</p>

<p>
  <strong>Validation:</strong>
  <%= @command.validation %>
</p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "tuto_railsdebutant", commands_path %> <!-- La méthode link_to est l’un des “helpers” (assistants) fournis par Rails. Il crée un hyperlien à partir du texte à afficher vers la destination, dans ce cas le chemin des commands. -->
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TutoRailsdebutant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>